/*
 * This source file was generated by the Gradle 'init' task
 */
package org.k8sui;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appTest() {
        App app = new App();
        assertNotNull(app);
    }
}
